[project]
name = "ai-engineering-portfolio"
version = "0.1.0"
description = "AI engineering portfolio work"
requires-python = ">=3.12"
dependencies = [
    "anthropic",
    "openai",
    "pydantic-ai",
    "python-dotenv",
    "ipykernel",
]

[tool.uv.workspace]
members = ["packages/*", "projects/*"]

[tool.uv]
package = false # the repo root itself isn't an installable package, it's a uv workspace
link-mode = "copy" # developing on a remote compute, uv preferred hardlinking isn't allowed, uv has to copy, making installs a bit slower, but that's it.
